# Site settings
title: 智慧水运
email: xw153@jsti.com aaron@rgxwang.com
description: > # this means to ignore newlines until "baseurl:"
  personal work plans
  知识分享
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rgxwang.com" # the base hostname & protocol for your site
twitter_username: aaron Xie
github_username:  rgxwang

# Build settings
markdown: kramdown
